# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:54
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventLog', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='log',
            old_name='extra',
            new_name='notes',
        ),
        migrations.RemoveField(
            model_name='log',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='log',
            name='object_id',
        ),
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
