# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2017-05-02 01:56
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('EventLog', '0004_auto_20170501_2155'),
    ]

    operations = [
        migrations.AlterField(
            model_name='log',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
